server:
  port: ${PORT:8005}
spring:
  application:
    name: registration-service
  cloud:
    consul:
      enabled: false
app:
  messaging:
    exchange:
      registration: "registration"
    routing-key:
      registration:
        event:
          registered: "registration.event.registered"
          resigned: "registration.event.resigned"
