spring:
  config:
    enabled: false
  cloud:
    consul:
      enabled: false
  zipkin:
    enabled: false
recaptcha:
  validation:
    # https://developers.google.com/recaptcha/docs/faq
    secret-key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
