version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./deployment/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_NODENAME: rabbit@localhost
    volumes:
      - ./deployment/data/rabbitmq:/var/lib/rabbitmq/
  keycloak:
    build: keycloak/themes
    image: keycloak
    restart: unless-stopped
    ports:
      - 9800:9800
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak?createDatabaseIfNotExist=true
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      KC_PROXY: edge
      KC_HTTP_PORT: 9800
      KC_HOSTNAME: auth.app.dev.crunchdao.com
      KC_HOSTNAME_STRICT_HTTPS: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: https://auth.app.dev.crunchdao.com/
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./deployment/data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  zipkin:
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - 9411:9411
  consul:
    image: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    volumes:
      - ./deployment/data/consul:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: [ "agent", "-server", "-ui", "-node=server-1", "-bootstrap-expect=1", "-client=0.0.0.0" ]
  achievement-service:
    image: crunchdao/achievement-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mongo
  api-key-service:
    image: crunchdao/api-key-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mongo
  auth-service:
    image: crunchdao/auth-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - keycloak
      - api-key-service
  avatar-service:
    image: crunchdao/avatar-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
  connection-service:
    image: crunchdao/connection-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mysql
  follow-service:
    image: crunchdao/follow-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mysql
  gateway:
    image: crunchdao/gateway
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
  graphql:
    image: crunchdao/graphql
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
  keycloak-service:
    image: crunchdao/keycloak-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - keycloak
  notification-service:
    image: crunchdao/notification-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mongo
  referral-service:
    image: crunchdao/referral-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mysql
  registration-service:
    image: crunchdao/registration-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - keycloak-service
  segment-analytics-service:
    image: crunchdao/segment-analytics-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
  user-service:
    image: crunchdao/user-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mongo
  model-service:
    image: crunchdao/model-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mysql
  round-service:
    image: crunchdao/round-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mongo
  submission-service:
    image: crunchdao/submission-service
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PORT=80
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=consul
    depends_on:
      - consul
      - mongo
  webapp:
    build:
      context: webapp
      args:
          SSR_BASE_URL: http://gateway
          KEYCLOAK_BASE_URL: https://auth.app.dev.crunchdao.com/
    image: crunchdao/webapp
    restart: unless-stopped
    ports:
      - 8001:80
    environment:
      - NUXT_PORT=80
