spring:
  config:
    enabled: false
  cloud:
    consul:
      enabled: false
  sleuth:
    enabled: false
  zipkin:
    enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
