server:
  port: ${PORT:8013}
spring:
  application:
    name: avatar-service
  cloud:
    consul:
      enabled: false
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        region: eu-west-1
app:
  avatar:
    bucket: datacrunch-com-public
    key-format: "/app/users/{userId}/avatar.png"
