keycloak:
  realm: app
  server-url: http://localhost:9800/
  client-id: backend
  client-secret: 9GaWzFnxHOtbZnMQj2dLdNpIYSMW3sud
#debug: true
#logger:
#  level:
#    org.springframework.security: TRACE
