spring:
  config:
    enabled: false
  cloud:
    consul:
      enabled: false
  sleuth:
    enabled: false
  zipkin:
    enabled: false
  data:
    mongodb:
      host: localhost
      uuid-representation: standard
      authentication-database: admin
      username: root
      password: password
      database: ${spring.application.name}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
