server:
  port: ${PORT:8010}
spring:
  application:
    name: achievement-service
  cloud:
    consul:
      enabled: false
app:
  messaging:
    exchange:
      achievement: "achievement"
    queue:
      achievement:
        command:
          increment: "achievement.command.increment.${spring.application.name}"
    routing-key:
      user:
        event:
          created: "user.event.created"
      connection:
        event:
          created: "connection.event.created"
      achievement:
        event:
          unlocked: "achievement.event.unlocked"
        command:
          increment: "achievement.command.increment"
