server:
  port: ${PORT:8010}
spring:
  application:
    name: achievement-service
  cloud:
    consul:
      enabled: false
app:
  messaging:
    exchange:
      user: "user"
      connection: "connection"
      achievement: "achievement"
      avatar: "avatar"
    queue:
      user:
        event:
          created: "user.event.created.${spring.application.name}"
      connection:
        event:
          created: "connection.event.created.${spring.application.name}"
      avatar:
        event:
          uploaded: "avatar.event.uploaded.${spring.application.name}"
    routing-key:
      user:
        event:
          created: "user.event.created"
      connection:
        event:
          created: "connection.event.created"
      achievement:
        event:
          unlocked: "achievement.event.unlocked"
      avatar:
        event:
          uploaded: "avatar.event.uploaded"
