server:
  port: ${PORT:8000}
spring:
  application:
    name: gateway
  config:
    import: "consul:"
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      config:
        enabled: true
        format: YAML
      discovery:
        enabled: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${random.uuid}
    gateway:
      default-filters:
      - name: Retry
        args:
          retries: 3
          series: # empty
          methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
          exceptions:
          - java.net.ConnectException
