server:
  port: ${PORT:8001}
spring:
  application:
    name: api-key-service
  cloud:
    loadbalancer:
      enabled: false
    consul:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
api-key:
  allowed-scopes:
    - api-key.read
    - api-key.write
