spring:
  config:
    enabled: false
  cloud:
    consul:
      enabled: false
  sleuth:
    enabled: false
  zipkin:
    enabled: false
  data:
    mongodb:
      host: localhost
      uuid-representation: standard
      authentication-database: admin
      username: root
      password: password
      database: api-key-service
