server:
  port: ${PORT:8001}
spring:
  application:
    name: api-key-service
  cloud:
    loadbalancer:
      enabled: false
    consul:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
api-key:
  allowed-scopes:
    - name: api-key.read
      description: List API-Keys.
    - name: api-key.write
      description: Create, update or delete API-Keys.
    - name: avatar.write
      description: Upload an avatar.
    - name: connection.write
      description: Connect, update or delete connections.
    - name: follow.write
      description: Follow other peoples.
    - name: notification.read
      description: List notifications.
    - name: notification.write
      description: Mark notifications as read.
    - name: referral.read
      description: List referrals.
