server:
  port: ${PORT:8008}
spring:
  application:
    name: segment-analytics-service
  cloud:
    consul:
      enabled: false
app:
  messaging:
    exchange:
      user: "user"
      connection: "connection"
      achievement: "achievement"
    queue:
      user:
        event:
          created: "user.event.created.${spring.application.name}"
          deleted: "user.event.deleted.${spring.application.name}"
      connection:
        event:
          created: "connection.event.created.${spring.application.name}"
          deleted: "connection.event.deleted.${spring.application.name}"
      achievement:
        event:
          unlocked: "achievement.event.unlocked.${spring.application.name}"
    routing-key:
      user:
        event:
          created: "user.event.created"
          deleted: "user.event.deleted"
      connection:
        event:
          created: "connection.event.created"
          deleted: "connection.event.deleted"
      achievement:
        event:
          unlocked: "achievement.event.unlocked"
segment:
  analytics:
    writeKey: ${SEGMENT_WRITE_KEY:}
