server:
  port: ${PORT:8003}
spring:
  application:
    name: user-service
  cloud:
    consul:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
app:
  messaging:
    exchange:
      user: "user"
    routing-key:
      user:
        event:
          created: "user.event.created"
          deleted: "user.event.deleted"
