name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 17
          java-distribution: adopt
          maven-version: 3.6.3
      
      - name: Build with Maven
        run: |
          mvn -version
          mvn --batch-mode --update-snapshots package